# Generated by Django 4.2 on 2023-05-09 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BinaryTree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.binarytree')),
            ],
        ),
        migrations.AddField(
            model_name='binarytree',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.parent'),
        ),
        migrations.AlterUniqueTogether(
            name='binarytree',
            unique_together={('name', 'parent_id', 'position')},
        ),
    ]
