# Generated by Django 4.2 on 2023-05-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BinaryTree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('parent_id', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('name', 'parent_id', 'position')},
            },
        ),
    ]
