# Generated by Django 4.2 on 2023-05-09 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='binarytree',
            unique_together={('parent_id', 'position')},
        ),
    ]
