# Generated by Django 4.2 on 2023-05-09 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_parrent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parrent',
            name='name',
        ),
        migrations.AddField(
            model_name='parrent',
            name='Name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.binarytree'),
        ),
    ]
